version: '3.1'
name: safehaven

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pgdata:
