on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop -c prepare
      - run: nix develop -c test_and_lint
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        with:
          images: ghcr.io/sagehavenmaps/safehaven
          tags: |
            type=ref,event=release
            type=semver,pattern={{version}}
          flavor: |
            latest=false
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
